<?php
require('src/switchPath.php');
require('src/sessionCtrl.php');
require('src/fonct.php');
require('src/connexion/model/fonctconnect.php');
require('src/connexion/model/pushToSession.php');
require('src/reqsql.php');
require('templates/head.php');
require('src/connexion/view/mConnexion.php');
require('templates/footer.php');
?>